[package]
name = "mshc"
version = "0.1.8"
edition = "2024"
authors = ["Markku Sukanen <markku.sukanen@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A tiny utility library…"
repository = "https://github.com/msukanen/mshc.git"

[dependencies]
mshc-derive = { path = "../mshc-derive", optional = true, version = "0.1.1" }
mshc-macro-shared = { path = "../mshc-macro-shared", version = "0.1.1" }
paste = "1.0.15"
proc-macro2 = "1.0.106"
quote = "1.0.46"
serde = { version = "1.0.229", features = ["derive"] }
syn = "2.0.118"

[features]
derive = ["dep:mshc-derive"]

[badges]
maintenance = { status = "experimental" }
