[package]
name = "mshc-derive"
version = "0.1.11"
edition = "2024"
authors = ["Markku Sukanen <markku.sukanen@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "proc-macros for mshc"

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.3"
mshc-macro-shared = { path = "../mshc-macro-shared", version = "0.1.1" }

[lib]
proc-macro = true

[features]
default = []
grade-f-to-sss = []
grade-a2e = []
